import type { Prisma } from '../../../server/generated/prisma/client';
import * as z from 'zod';
import { ExpenseWhereInputObjectSchema as ExpenseWhereInputObjectSchema } from './objects/ExpenseWhereInput.schema';
import { ExpenseOrderByWithAggregationInputObjectSchema as ExpenseOrderByWithAggregationInputObjectSchema } from './objects/ExpenseOrderByWithAggregationInput.schema';
import { ExpenseScalarWhereWithAggregatesInputObjectSchema as ExpenseScalarWhereWithAggregatesInputObjectSchema } from './objects/ExpenseScalarWhereWithAggregatesInput.schema';
import { ExpenseScalarFieldEnumSchema } from './enums/ExpenseScalarFieldEnum.schema';
import { ExpenseCountAggregateInputObjectSchema as ExpenseCountAggregateInputObjectSchema } from './objects/ExpenseCountAggregateInput.schema';
import { ExpenseMinAggregateInputObjectSchema as ExpenseMinAggregateInputObjectSchema } from './objects/ExpenseMinAggregateInput.schema';
import { ExpenseMaxAggregateInputObjectSchema as ExpenseMaxAggregateInputObjectSchema } from './objects/ExpenseMaxAggregateInput.schema';
import { ExpenseAvgAggregateInputObjectSchema as ExpenseAvgAggregateInputObjectSchema } from './objects/ExpenseAvgAggregateInput.schema';
import { ExpenseSumAggregateInputObjectSchema as ExpenseSumAggregateInputObjectSchema } from './objects/ExpenseSumAggregateInput.schema';

export const ExpenseGroupBySchema: z.ZodType<Prisma.ExpenseGroupByArgs> = z.object({ where: ExpenseWhereInputObjectSchema.optional(), orderBy: z.union([ExpenseOrderByWithAggregationInputObjectSchema, ExpenseOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ExpenseScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ExpenseScalarFieldEnumSchema), _count: z.union([ z.literal(true), ExpenseCountAggregateInputObjectSchema ]).optional(), _min: ExpenseMinAggregateInputObjectSchema.optional(), _max: ExpenseMaxAggregateInputObjectSchema.optional(), _avg: ExpenseAvgAggregateInputObjectSchema.optional(), _sum: ExpenseSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ExpenseGroupByArgs>;

export const ExpenseGroupByZodSchema = z.object({ where: ExpenseWhereInputObjectSchema.optional(), orderBy: z.union([ExpenseOrderByWithAggregationInputObjectSchema, ExpenseOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ExpenseScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ExpenseScalarFieldEnumSchema), _count: z.union([ z.literal(true), ExpenseCountAggregateInputObjectSchema ]).optional(), _min: ExpenseMinAggregateInputObjectSchema.optional(), _max: ExpenseMaxAggregateInputObjectSchema.optional(), _avg: ExpenseAvgAggregateInputObjectSchema.optional(), _sum: ExpenseSumAggregateInputObjectSchema.optional() }).strict();