import type { Prisma } from '../../../server/generated/prisma/client';
import * as z from 'zod';
import { RevenueWhereInputObjectSchema as RevenueWhereInputObjectSchema } from './objects/RevenueWhereInput.schema';
import { RevenueOrderByWithAggregationInputObjectSchema as RevenueOrderByWithAggregationInputObjectSchema } from './objects/RevenueOrderByWithAggregationInput.schema';
import { RevenueScalarWhereWithAggregatesInputObjectSchema as RevenueScalarWhereWithAggregatesInputObjectSchema } from './objects/RevenueScalarWhereWithAggregatesInput.schema';
import { RevenueScalarFieldEnumSchema } from './enums/RevenueScalarFieldEnum.schema';
import { RevenueCountAggregateInputObjectSchema as RevenueCountAggregateInputObjectSchema } from './objects/RevenueCountAggregateInput.schema';
import { RevenueMinAggregateInputObjectSchema as RevenueMinAggregateInputObjectSchema } from './objects/RevenueMinAggregateInput.schema';
import { RevenueMaxAggregateInputObjectSchema as RevenueMaxAggregateInputObjectSchema } from './objects/RevenueMaxAggregateInput.schema';
import { RevenueAvgAggregateInputObjectSchema as RevenueAvgAggregateInputObjectSchema } from './objects/RevenueAvgAggregateInput.schema';
import { RevenueSumAggregateInputObjectSchema as RevenueSumAggregateInputObjectSchema } from './objects/RevenueSumAggregateInput.schema';

export const RevenueGroupBySchema: z.ZodType<Prisma.RevenueGroupByArgs> = z.object({ where: RevenueWhereInputObjectSchema.optional(), orderBy: z.union([RevenueOrderByWithAggregationInputObjectSchema, RevenueOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RevenueScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RevenueScalarFieldEnumSchema), _count: z.union([ z.literal(true), RevenueCountAggregateInputObjectSchema ]).optional(), _min: RevenueMinAggregateInputObjectSchema.optional(), _max: RevenueMaxAggregateInputObjectSchema.optional(), _avg: RevenueAvgAggregateInputObjectSchema.optional(), _sum: RevenueSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.RevenueGroupByArgs>;

export const RevenueGroupByZodSchema = z.object({ where: RevenueWhereInputObjectSchema.optional(), orderBy: z.union([RevenueOrderByWithAggregationInputObjectSchema, RevenueOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RevenueScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RevenueScalarFieldEnumSchema), _count: z.union([ z.literal(true), RevenueCountAggregateInputObjectSchema ]).optional(), _min: RevenueMinAggregateInputObjectSchema.optional(), _max: RevenueMaxAggregateInputObjectSchema.optional(), _avg: RevenueAvgAggregateInputObjectSchema.optional(), _sum: RevenueSumAggregateInputObjectSchema.optional() }).strict();